In [20]:
function project_monomial(f, n, lb, ub)
    # step 1: make the grid
    x = collect(range(lb, ub, n))
        
    # step 2: evaluate the function at the grid
    y = f.(x)
    
    # step 3: basis function at the grid
    ϕ = zeros(n,1)
    for col in 1:n
        f_col(x) = x^(col-1)
        col_output = f_col.(x)
        ϕ = hcat(ϕ, col_output)
    end
    ϕ = ϕ[:, 1:end .!= 1]
    
    # step 4: get c
    c = ϕ \ y
    
    return c
end

project_monomial (generic function with 1 method)

In [24]:
project_monomial(x -> x^3, 4,-4,1)
    

4-element Vector{Float64}:
  5.921189464667496e-16
  4.44089209850063e-16
 -8.141635513917813e-16
  0.9999999999999998

In [15]:
# step 3: basis function at the grid
ϕ = zeros(10,1)
    for col in 1:10
        f_col(x) = x^col
        
        col_output = f_col.(x)
        ϕ = hcat(ϕ, col_output)
    end

In [17]:
ϕ = ϕ[:, 1:end .!= 1]

10×10 Matrix{Float64}:
  0.0        0.0         0.0          0.0      …      0.0           0.0
  1.11111    1.23457     1.37174      1.52416         2.58117       2.86797
  2.22222    4.93827    10.9739      24.3865       1321.56       2936.8
  3.33333   11.1111     37.037      123.457       50805.3           1.69351e5
  4.44444   19.7531     87.7915     390.184           6.76639e5     3.00729e6
  5.55556   30.8642    171.468      952.599    …      5.04136e6     2.80075e7
  6.66667   44.4444    296.296     1975.31            2.60123e7     1.73415e8
  7.77778   60.4938    470.508     3659.5             1.0416e8      8.10131e8
  8.88889   79.0123    702.332     6242.95            3.46439e8     3.07946e9
 10.0      100.0      1000.0      10000.0             1.0e9         1.0e10

In [29]:
coll_points = range(0, 10, 10)
basis_functions = [coll_points.^degree for degree = 0:10-1]
hcat(basis_functions...)

10×10 Matrix{Float64}:
 1.0   0.0        0.0         0.0      …      0.0            0.0
 1.0   1.11111    1.23457     1.37174         2.32306        2.58117
 1.0   2.22222    4.93827    10.9739        594.703       1321.56
 1.0   3.33333   11.1111     37.037       15241.6        50805.3
 1.0   4.44444   19.7531     87.7915          1.52244e5      6.76639e5
 1.0   5.55556   30.8642    171.468    …      9.07444e5      5.04136e6
 1.0   6.66667   44.4444    296.296           3.90184e6      2.60123e7
 1.0   7.77778   60.4938    470.508           1.3392e7       1.0416e8
 1.0   8.88889   79.0123    702.332           3.89744e7      3.46439e8
 1.0  10.0      100.0      1000.0             1.0e8          1.0e9

In [32]:
coll_points.^2

10-element Vector{Float64}:
   0.0
   1.234567901234568
   4.938271604938272
  11.111111111111112
  19.75308641975309
  30.864197530864196
  44.44444444444445
  60.49382716049382
  79.01234567901236
 100.0

In [ ]:
function cheb_polys(n,x)
    T_prev(x) = 1
    T_now(x) = x
    for n in 2:n
        T_next(x) = 2*x*T_now(x) - T_prev(x)
        T_prev(x) = T_now(x)
        T_now() = 
    end
end